###
# * Minimal Setup
# * Prebuilt image where URL is specified during BUILD.
# * Does not include Python, Poetry, or the project files. Serves pre-built static sites with Nginx.
###
services:

  hexproof-docs:
    image: investigamer/hexproof-docs:latest
    container_name: hexproof-docs
    ports:
      - "8100:80"
